spring:
  datasource:
    url: jdbc:h2:mem:techni
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
#  datasource:
#    url: jdbc:postgresql://localhost:5432/techni
#    username: postgres
#    password: 123456a.
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#  mvc:
#    throw-exception-if-no-handler-found : true
#    static-path-pattern: /static
#
  h2:
    console:
      enabled: true
#custom:
#  test: 10
#folders:
#  pdf: 'C:\techni\pdf\'

